--
-- Create Schema Script 
--   Database Version   : 12.2.0.1.0 
--   TOAD Version       : 9.6.1.1 
--   DB Connect String  : ACAD 
--   Schema             : PROVEDORES 
--   Script Created by  : PROVEDORES 
--   Script Created at  : 21/08/2019 8:27:05 a. m. 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Functions: 3       Lines of Code: 76 
--   Indexes: 12        Columns: 12         
--   Procedures: 8      Lines of Code: 303 
--   Sequences: 6 
--   Tables: 12         Columns: 53         Constraints: 23     
--   Views: 5           


CREATE SEQUENCE ID_CARGA
  START WITH 8396
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ID_EMPRESA
  START WITH 1022
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ID_JURIDICA
  START WITH 385
  MAXVALUE 999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ID_NATURAL
  START WITH 637
  MAXVALUE 999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ID_REVISION
  START WITH 6179
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE ID_USUARIO
  START WITH 1005
  MAXVALUE 999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE TABLE PROFESION
(
  ID_PROFESION   INTEGER,
  NOM_PROFESION  VARCHAR2(150 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCUMENTO
(
  ID_DOCUMENTO   INTEGER,
  NOM_DOCUMENTO  VARCHAR2(150 CHAR),
  ID_TIPO        INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USUARIO
(
  ID_EMPRESA      INTEGER,
  DOCUMENTO       VARCHAR2(50 CHAR),
  CLAVE           VARCHAR2(200 CHAR),
  FECHA_CREACION  DATE                          DEFAULT sysdate,
  ID_USUARIO      INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ACTVIDAD_ECO
(
  ID_ACTIVIDAD   INTEGER,
  NOM_ACTIVIDAD  VARCHAR2(350 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ESTADO
(
  ID_ESTADO   INTEGER,
  NOM_ESTADO  VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EMPRESA
(
  ID_EMPRESA      INTEGER,
  NOM_EMPRESA     VARCHAR2(200 CHAR)            NOT NULL,
  NIT             VARCHAR2(50 CHAR)             NOT NULL,
  DIRECCION       VARCHAR2(150 CHAR)            NOT NULL,
  EMAIL           VARCHAR2(50 CHAR)             NOT NULL,
  ID_TIPO         INTEGER                       NOT NULL,
  IP              VARCHAR2(50 CHAR)             NOT NULL,
  FECHA_REGISTRO  DATE                          DEFAULT SYSDATE               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DOCS_CARGADO
(
  ID_CARGA      INTEGER,
  ID_DOCUMENTO  INTEGER,
  ID_EMPRESA    INTEGER,
  RUTA          VARCHAR2(50 CHAR),
  FECHA_CARGA   DATE                            DEFAULT sysdate,
  IP            VARCHAR2(50 CHAR),
  VERSION       INTEGER,
  ID_ESTADO     INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EMPRESA_NAT
(
  ID_NATURAL    INTEGER,
  ID_EMPRESA    INTEGER,
  COPNIA        VARCHAR2(20 CHAR),
  LIBRETA       VARCHAR2(20 CHAR),
  ID_PROFESION  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE EMPRESA_JUR
(
  ID_JURIDICA       INTEGER,
  ID_EMPRESA        INTEGER,
  ID_ACTIVIDAD      INTEGER,
  NOMREPRESENTANTE  VARCHAR2(150 CHAR),
  CEDREPRESENTANE   VARCHAR2(20 CHAR),
  DIRECCIONPRINCI   VARCHAR2(100 CHAR),
  NATURALEZA        VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPO_EMPRESA
(
  ID_TIPO   INTEGER,
  NOM_TIPO  VARCHAR2(150 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE REVISION
(
  ID_REVISION     INTEGER,
  ID_CARGA        INTEGER,
  FECHA_REVISION  DATE                          DEFAULT sysdate,
  USUARIO         VARCHAR2(150 CHAR),
  ID_ESTADO       INTEGER,
  MOTIVO          VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USUARIO_ADMON
(
  DOC   VARCHAR2(50 CHAR),
  PASS  VARCHAR2(200 CHAR),
  TIPO  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX TIPO_EMPRESA_PK ON TIPO_EMPRESA
(ID_TIPO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX EMPRESA_PK ON EMPRESA
(ID_EMPRESA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX DOCUMENTOS_PK ON DOCUMENTO
(ID_DOCUMENTO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX USUARIO_PK ON USUARIO
(ID_USUARIO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX EMPRESA_NAT_PK ON EMPRESA_NAT
(ID_NATURAL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX EMPRESA_JUR_PK ON EMPRESA_JUR
(ID_JURIDICA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX DOCS_CARGADOS_PK ON DOCS_CARGADO
(ID_CARGA)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PROFESION_PK ON PROFESION
(ID_PROFESION)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ACTVIDAD_ECO_PK ON ACTVIDAD_ECO
(ID_ACTIVIDAD)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ESTADOS_PK ON ESTADO
(ID_ESTADO)
LOGGING
NOPARALLEL;


CREATE OR REPLACE PROCEDURE            UPD_EMPRESA_NAT ( VNOMBRE VARCHAR2, VDIRECCION VARCHAR2, VEMAIL VARCHAR2, VID_EMPRESA INTEGER,  
                                                         VIP VARCHAR2,  VLIBRETA VARCHAR2, VCOPNIA VARCHAR2, IID_PROFESION INTEGER, RESULT OUT VARCHAR2   ) IS
    
    ID_EMPPRESA_TMP INTEGER;
    CONT_EXISTE INTEGER;
    RAND VARCHAR2(6);
        
BEGIN
    
    SELECT COUNT( * ) INTO CONT_EXISTE
    FROM   EMPRESA E
    WHERE  ID_EMPRESA = VID_EMPRESA;    


    IF (  CONT_EXISTE = 0 ) THEN 
        RESULT := 'La empresa no se encuentra, por favor inicie sesion para modificar sus datos'; 
        RETURN;        
    END IF;

    UPDATE PROVEDORES.EMPRESA 
    SET NOM_EMPRESA = VNOMBRE, 
        DIRECCION =  VDIRECCION, 
        EMAIL = VEMAIL,
        IP = VIP 
    WHERE ID_EMPRESA = VID_EMPRESA;
    
    UPDATE PROVEDORES.EMPRESA_NAT 
    SET  COPNIA =VCOPNIA, 
         LIBRETA = VLIBRETA, 
         ID_PROFESION =IID_PROFESION
    WHERE ID_EMPRESA = VID_EMPRESA;
    
    RESULT := 'OK';    
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            DEL_USUARIO( VNIT VARCHAR2, RESULT OUT VARCHAR2  ) IS

    I_EMPRESA INTEGER;

BEGIN 
        SELECT COUNT( E.NIT ) INTO I_EMPRESA  
        FROM   EMPRESA E
        WHERE  E.NIT = VNIT;
        
        IF ( I_EMPRESA = 0 ) THEN
            RESULT := 'La empresa no se encuentra en nuestra de datos, revise los datos e ingreselo nuevamente !!!';
            RETURN;
        END IF;

        DELETE
        FROM PROVEDORES.REVISION R
        WHERE R.ID_CARGA IN (  SELECT DC.ID_CARGA
                               FROM PROVEDORES.DOCS_CARGADO DC
                               WHERE ID_EMPRESA IN (  SELECT ID_EMPRESA 
                                                      FROM  PROVEDORES.EMPRESA  
                                                      WHERE NIT = VNIT ) );

        DELETE
        FROM PROVEDORES.DOCS_CARGADO
        WHERE ID_EMPRESA IN (  SELECT ID_EMPRESA 
                               FROM  PROVEDORES.EMPRESA  
                               WHERE NIT = VNIT );


        DELETE
        FROM PROVEDORES.USUARIO 
        WHERE ID_EMPRESA IN (  SELECT ID_EMPRESA 
                                FROM  PROVEDORES.EMPRESA  
                                WHERE NIT = VNIT );                     
                                
        DELETE
        FROM PROVEDORES.EMPRESA_JUR 
        WHERE ID_EMPRESA IN (  SELECT ID_EMPRESA 
                                FROM  PROVEDORES.EMPRESA  
                                WHERE NIT = VNIT );                      
                                
        DELETE
        FROM PROVEDORES.EMPRESA_NAT 
        WHERE ID_EMPRESA IN (  SELECT ID_EMPRESA 
                                FROM  PROVEDORES.EMPRESA  
                                WHERE NIT = VNIT );                        
                                
        DELETE
        FROM  PROVEDORES.EMPRESA  
        WHERE NIT = VNIT;


END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            ADD_EMPRESA_NAT ( VNOMBRE VARCHAR2, VNIT VARCHAR2, VDIRECCION VARCHAR2, VEMAIL VARCHAR2,  
                                              VIP VARCHAR2,  VLIBRETA VARCHAR2, VCOPNIA VARCHAR2, IID_PROFESION INTEGER, RESULT OUT VARCHAR2   ) IS
    
    ID_EMPPRESA_TMP INTEGER;
    CONT_EXISTE INTEGER;
        
BEGIN
    
    SELECT COUNT( * ) INTO CONT_EXISTE
    FROM   EMPRESA E
    WHERE  E.NIT = VNIT;    


    IF (  CONT_EXISTE > 0 ) THEN 
        RESULT := 'La cedula/nit ya se encuentra registrada, por favor inicie sesion para modificar sus datos'; 
        RETURN;        
    END IF;
    
    SELECT ID_EMPRESA.NEXTVAL INTO ID_EMPPRESA_TMP
    FROM DUAL ;

    INSERT INTO PROVEDORES.EMPRESA ( ID_EMPRESA, NOM_EMPRESA, NIT, DIRECCION, EMAIL, ID_TIPO, IP) 
    VALUES ( ID_EMPPRESA_TMP, VNOMBRE , VNIT , VDIRECCION , VEMAIL , 0, VIP );

    INSERT INTO PROVEDORES.EMPRESA_NAT ( ID_NATURAL, ID_EMPRESA, COPNIA, LIBRETA, ID_PROFESION) 
    VALUES ( ID_NATURAL.NEXTVAL, ID_EMPPRESA_TMP, VCOPNIA, VLIBRETA, IID_PROFESION  ); 
    
    INSERT INTO PROVEDORES.USUARIO ( ID_EMPRESA, DOCUMENTO, CLAVE,  ID_USUARIO) 
    VALUES ( ID_EMPPRESA_TMP, VNIT ,  null , ID_USUARIO.NEXTVAL  );
    
    RESULT := 'OK';
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            ADD_EMPRESA_JUR ( VNOMBRE VARCHAR2, VNIT VARCHAR2, VDIRECCION VARCHAR2, VEMAIL VARCHAR2,  VIP VARCHAR2,  VNATURALEZA VARCHAR2,
                                              IID_ACTIVIDAD INTEGER, VNOMBREREP VARCHAR2, VCEDREP VARCHAR2, VDIR_PRINCI VARCHAR2, RESULT OUT VARCHAR2   ) IS
    
    ID_EMPPRESA_TMP INTEGER;        
    CONT_EXISTE INTEGER;
    CONT_ACTIVIDAD INTEGER;
    
    
BEGIN
    
    SELECT COUNT( * ) INTO CONT_EXISTE
    FROM   EMPRESA E
    WHERE  E.NIT = VNIT;    

    SELECT COUNT( AC.ID_ACTIVIDAD ) INTO CONT_ACTIVIDAD
    FROM   ACTVIDAD_ECO AC
    WHERE  AC.ID_ACTIVIDAD = IID_ACTIVIDAD;

    IF (  CONT_ACTIVIDAD=0 ) THEN 
        RESULT := 'La Actividad economica no existe, por favor seleccione una de la lista';    
        RETURN;
    END IF;


    IF (  CONT_EXISTE > 0 ) THEN 
        RESULT := 'La cedula/nit ya se encuentra registrada, por favor inicie sesion para modificar sus datos'; 
        RETURN;        
    END IF;
    
    SELECT ID_EMPRESA.NEXTVAL INTO ID_EMPPRESA_TMP
    FROM DUAL ;

    INSERT INTO PROVEDORES.EMPRESA ( ID_EMPRESA, NOM_EMPRESA, NIT, DIRECCION, EMAIL, ID_TIPO, IP) 
    VALUES ( ID_EMPPRESA_TMP, VNOMBRE , VNIT , VDIRECCION , VEMAIL , 1, VIP );

    INSERT INTO PROVEDORES.EMPRESA_JUR ( ID_JURIDICA, ID_EMPRESA, ID_ACTIVIDAD, NOMREPRESENTANTE, CEDREPRESENTANE, DIRECCIONPRINCI, NATURALEZA) 
    VALUES ( ID_JURIDICA.NEXTVAL, ID_EMPPRESA_TMP, IID_ACTIVIDAD, VNOMBREREP, VCEDREP, VDIR_PRINCI, VNATURALEZA );
     
    INSERT INTO PROVEDORES.USUARIO ( ID_EMPRESA, DOCUMENTO, CLAVE,  ID_USUARIO) 
    VALUES ( ID_EMPPRESA_TMP, VNIT ,  null , ID_USUARIO.NEXTVAL  );
    
    RESULT := 'OK';
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            ADD_DOCUMENTO( IID_DOCUMENTO INTEGER, IID_EMPRESA INTEGER, VRUTA VARCHAR2, VIP VARCHAR2, RESULT OUT VARCHAR2  ) IS

    NEXTVERSION INTEGER;
    CONT_EMPRESA INTEGER;
    CONT_DOCUMENTO INTEGER;

BEGIN


    SELECT COUNT( ID_EMPRESA ) INTO CONT_EMPRESA
    FROM   EMPRESA 
    WHERE  ID_EMPRESA = IID_EMPRESA;

    IF ( CONT_EMPRESA = 0 ) THEN
        RESULT := 'Su sesion ha expirado, inicie de nuevo e intentelo mas tarde';   
        RETURN;
    END IF;


    SELECT COUNT( ID_DOCUMENTO) INTO CONT_DOCUMENTO
    FROM   DOCUMENTO 
    WHERE  ID_DOCUMENTO = IID_DOCUMENTO;
    
    IF ( CONT_DOCUMENTO = 0 ) THEN
        RESULT := 'El documento no existe, inicie sesion de nuevo e intentelo mas tarde';   
        RETURN;
    END IF;
    

    SELECT COUNT( ID_CARGA) INTO NEXTVERSION
    FROM   DOCS_CARGADO 
    WHERE  ID_DOCUMENTO = IID_DOCUMENTO AND ID_EMPRESA = IID_EMPRESA;

    INSERT INTO PROVEDORES.DOCS_CARGADO ( ID_CARGA, ID_DOCUMENTO, ID_EMPRESA, RUTA, IP, VERSION, ID_ESTADO) 
    VALUES ( ID_CARGA.NEXTVAL , IID_DOCUMENTO , IID_EMPRESA ,VRUTA, VIP, ( NEXTVERSION + 1 ) , 0  );
    
    RESULT := 'OK';

END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            UPD_CONTRA( VNIT VARCHAR2, SALE OUT VARCHAR2  ) IS
    
    PASS VARCHAR2(10);    
    IID_EMPRESA NUMBER;
    CONTEO INTEGER;
    
BEGIN 

    SELECT COUNT(*) INTO CONTEO
    FROM EMPRESA 
    WHERE NIT =VNIT;

    IF ( CONTEO = 0 ) THEN 
        SALE := 'No existe una empresa con el nit diligenciado, registre el nuevo usuario y se le asignara una contraseña.';
        RETURN;    
    END IF;


    PASS := dbms_random.string('X', 6);
    
    SELECT ID_EMPRESA INTO IID_EMPRESA
    FROM EMPRESA 
    WHERE NIT =VNIT;
    
    UPDATE USUARIO  
    SET    CLAVE = REGIS.MD5(PASS)
    WHERE  IID_EMPRESA = ID_EMPRESA;
    
    SALE := PASS;    
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE            UPD_EMPRESA_JUR ( VNOMBRE VARCHAR2, VDIRECCION VARCHAR2, VEMAIL VARCHAR2, VID_EMPRESA INTEGER, VIP VARCHAR2, VNATURALEZA VARCHAR2,
                                              IID_ACTIVIDAD INTEGER, VNOMBREREP VARCHAR2, VCEDREP VARCHAR2, VDIR_PRINCI VARCHAR2, RESULT OUT VARCHAR2   ) IS
    
    ID_EMPPRESA_TMP INTEGER;
    CONT_EXISTE INTEGER;
    RAND VARCHAR2(6);
    CONT_ACTIVIDAD INTEGER;    
    
BEGIN
    
    SELECT COUNT( * ) INTO CONT_EXISTE
    FROM   EMPRESA E
    WHERE  ID_EMPRESA = VID_EMPRESA;    

    SELECT COUNT( AC.ID_ACTIVIDAD ) INTO CONT_ACTIVIDAD
    FROM   ACTVIDAD_ECO AC
    WHERE  AC.ID_ACTIVIDAD = IID_ACTIVIDAD;

    IF (  CONT_ACTIVIDAD=0 ) THEN 
        RESULT := 'La Actividad economica no existe, por favor seleccione una de la lista';    
        RETURN;
    END IF;

    IF (  CONT_EXISTE = 0 ) THEN 
        RESULT := 'La empresa no se encuentra, por favor inicie sesion para modificar sus datos'; 
        RETURN;        
    END IF;

    UPDATE PROVEDORES.EMPRESA 
    SET NOM_EMPRESA = VNOMBRE, 
        DIRECCION =  VDIRECCION, 
        EMAIL = VEMAIL,
        IP = VIP 
    WHERE ID_EMPRESA = VID_EMPRESA;
    
    UPDATE PROVEDORES.EMPRESA_JUR
    SET    ID_ACTIVIDAD     = IID_ACTIVIDAD,
           NOMREPRESENTANTE = VNOMBREREP,
           CEDREPRESENTANE  = VCEDREP,
           DIRECCIONPRINCI  = VDIR_PRINCI,
           NATURALEZA       = VNATURALEZA
    WHERE  ID_EMPRESA       = VID_EMPRESA;
    
    RESULT := 'OK';    
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE ADD_REVISION( IID_CARGA NUMBER, VUSUARIO VARCHAR2, VESTADO VARCHAR2, VMOTIVO VARCHAR2, RESULT OUT VARCHAR  ) IS 

    CONTEO INTEGER;
BEGIN

    SELECT COUNT (ID_CARGA) INTO CONTEO 
    FROM  DOCS_CARGADO 
    WHERE ID_CARGA = IID_CARGA AND ID_ESTADO = 0;

    IF ( CONTEO = 0 ) THEN 
        RESULT:= 'El documento no se encuentra en proceso de revision, refresque la pagina e intentelo de nuevo !!!';
        RETURN;
    END IF;

    INSERT INTO PROVEDORES.REVISION (ID_REVISION, ID_CARGA, USUARIO, ID_ESTADO, MOTIVO) 
    VALUES ( ID_REVISION.NEXTVAL, IID_CARGA, VUSUARIO, VESTADO, VMOTIVO );
    
    UPDATE DOCS_CARGADO 
    SET    ID_ESTADO = VESTADO
    WHERE  ID_CARGA = IID_CARGA;
    
    RESULT := 'OK';
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE FUNCTION GET_ESTADO_NOMBRE(  IID_EMPRESA number, IID_DOCUMENTO number  ) RETURN VARCHAR2 IS

    RESULT VARCHAR2(50);
    CONTEO INTEGER;

BEGIN 
    
    SELECT COUNT( DC.ID_CARGA ) INTO CONTEO
    FROM  DOCS_CARGADO DC
    WHERE DC.ID_EMPRESA = IID_EMPRESA AND DC.ID_DOCUMENTO = IID_DOCUMENTO;

    IF ( CONTEO =0 ) THEN 
        RETURN '. Sin carga';
    END IF;

    SELECT E.NOM_ESTADO || ' ' || TO_CHAR(DC.FECHA_CARGA, 'DD/MM/YY HH:MI'  ) INTO RESULT  
    FROM DOCS_CARGADO DC  
    INNER JOIN ESTADO E ON E.ID_ESTADO = DC.ID_ESTADO  
    WHERE DC.ID_EMPRESA = IID_EMPRESA AND DC.ID_DOCUMENTO = IID_DOCUMENTO  
    HAVING DC.VERSION = (SELECT MAX(DC1.VERSION) FROM DOCS_CARGADO DC1 WHERE DC1.ID_EMPRESA = DC.ID_EMPRESA AND DC1.ID_DOCUMENTO = DC.ID_DOCUMENTO )  
    GROUP BY DC.VERSION, E.NOM_ESTADO, DC.FECHA_CARGA, DC.ID_EMPRESA, DC.ID_DOCUMENTO;
    
    RETURN RESULT;
    
END     ;


/*
SELECT GET_ESTADO_NOMBRE(  :IID_EMPRESA , :IID_DOCUMENTO)
FROM   DUAL*/
/

SHOW ERRORS;


CREATE OR REPLACE FUNCTION IS_DOC_CARGADO( DOC VARCHAR2, EMPRESA VARCHAR2 ) RETURN NUMBER IS

    CONTEO INTEGER;
    
BEGIN

    SELECT COUNT( DC.ID_CARGA ) INTO CONTEO
    FROM   DOCS_CARGADO DC
    WHERE  DC.ID_DOCUMENTO = DOC AND DC.ID_EMPRESA = EMPRESA AND DC.ID_ESTADO = 0;
    
    RETURN CONTEO;
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE FUNCTION GET_PENULTIMO_ESTADO( IID_EMPRESA INTEGER, IID_DOCUMENTO INTEGER ) RETURN INTEGER IS 
    
    CONTEO INTEGER;
    LAST_VERSION INTEGER;
    TMPESTADO INTEGER;
    
    
BEGIN 

    SELECT COUNT( DC.ID_CARGA ) INTO CONTEO
    FROM  DOCS_CARGADO DC
    WHERE DC.ID_EMPRESA = IID_EMPRESA AND DC.ID_DOCUMENTO = IID_DOCUMENTO;

    IF ( CONTEO =0 ) THEN 
        RETURN 0;
    END IF;

    SELECT ( MAX( DC.VERSION ) - 1 ) INTO LAST_VERSION
    FROM  DOCS_CARGADO DC
    WHERE DC.ID_EMPRESA = IID_EMPRESA AND DC.ID_DOCUMENTO = IID_DOCUMENTO;
    
    IF ( LAST_VERSION = 0  ) THEN
         RETURN 0;   
    END IF;
    
    
    SELECT MAX( DC.ID_ESTADO )  INTO TMPESTADO
    FROM  DOCS_CARGADO DC
    WHERE DC.ID_EMPRESA = IID_EMPRESA AND DC.ID_DOCUMENTO = IID_DOCUMENTO AND DC.VERSION = LAST_VERSION ;
    
    RETURN TMPESTADO;
    
END;
/

SHOW ERRORS;


CREATE OR REPLACE VIEW EMPRESA_NATURAL
AS 
SELECT TO_NUMBER (e.id_empresa) id_empresa, INITCAP(nom_empresa) nom_empresa, nit, LOWER(direccion),
          lower(email), TO_NUMBER (en.id_natural) id_natural, copnia, libreta,
          TO_CHAR (id_profesion) id_profesion
     FROM empresa e INNER JOIN empresa_nat en ON e.id_empresa = en.id_empresa;


CREATE OR REPLACE VIEW EMPRESA_JURIDICA
AS 
SELECT TO_NUMBER (e.id_empresa) id_empresa, INITCAP(nom_empresa), nit, lower(direccion) direccion,
          lower(email) email, en.id_juridica, en.cedrepresentane, lower(en.direccionprinci) direccionprinci,
          TO_CHAR(en.id_actividad) id_actividad, en.naturaleza, INITCAP(en.nomrepresentante) nomrepresentante
     FROM empresa e INNER JOIN empresa_jur en ON e.id_empresa = en.id_empresa;


CREATE OR REPLACE VIEW EMPRESA_NATURAL_DETALLE
AS 
SELECT TO_NUMBER (e.id_empresa) id_empresa, INITCAP(nom_empresa) nom_empresa, nit, LOWER(direccion) direccion ,
          LOWER(email) email , copnia, libreta, p.nom_profesion, id_natural,
          TO_CHAR (en.id_profesion) id_profesion
     FROM empresa e INNER JOIN empresa_nat en ON e.id_empresa = en.id_empresa
          INNER JOIN profesion p ON p.id_profesion = en.id_profesion;


CREATE OR REPLACE VIEW JURIDICA_DETALLE
AS 
SELECT TO_NUMBER (e.id_empresa) id_empresa, INITCAP(nom_empresa), nit, LOWER(direccion) direccion,
          LOWER(email) email, en.id_juridica, en.cedrepresentane, LOWER(en.direccionprinci) direccionprinci,
          TO_CHAR(EN.id_actividad) id_actividad, en.naturaleza, INITCAP(en.nomrepresentante) nomrepresentante,
          ae.nom_actividad
     FROM empresa e INNER JOIN empresa_jur en ON e.id_empresa = en.id_empresa
          INNER JOIN actvidad_eco ae ON ae.id_actividad = en.id_actividad;


CREATE OR REPLACE VIEW DOCUMENTO_RESUMEN
AS 
SELECT dc.ruta, dc.fecha_carga, dc.VERSION, dc.id_estado, d.nom_documento,
          INITCAP(e.nom_empresa) nom_empresa, es.nom_estado, dc.id_documento, dc.id_empresa,
          dc.id_carga
     FROM docs_cargado dc INNER JOIN documento d
          ON d.id_documento = dc.id_documento
          INNER JOIN empresa e ON e.id_empresa = dc.id_empresa
          INNER JOIN estado es ON es.id_estado = dc.id_estado;


ALTER TABLE PROFESION ADD (
  CONSTRAINT PROFESION_PK
 PRIMARY KEY
 (ID_PROFESION));

ALTER TABLE DOCUMENTO ADD (
  CONSTRAINT DOCUMENTOS_PK
 PRIMARY KEY
 (ID_DOCUMENTO));

ALTER TABLE USUARIO ADD (
  CONSTRAINT USUARIO_PK
 PRIMARY KEY
 (ID_USUARIO));

ALTER TABLE ACTVIDAD_ECO ADD (
  CONSTRAINT ACTVIDAD_ECO_PK
 PRIMARY KEY
 (ID_ACTIVIDAD));

ALTER TABLE ESTADO ADD (
  CONSTRAINT ESTADOS_PK
 PRIMARY KEY
 (ID_ESTADO));

ALTER TABLE EMPRESA ADD (
  CONSTRAINT EMPRESA_PK
 PRIMARY KEY
 (ID_EMPRESA));

ALTER TABLE DOCS_CARGADO ADD (
  CONSTRAINT DOCS_CARGADOS_PK
 PRIMARY KEY
 (ID_CARGA));

ALTER TABLE EMPRESA_NAT ADD (
  CONSTRAINT EMPRESA_NAT_PK
 PRIMARY KEY
 (ID_NATURAL));

ALTER TABLE EMPRESA_JUR ADD (
  CONSTRAINT EMPRESA_JUR_PK
 PRIMARY KEY
 (ID_JURIDICA));

ALTER TABLE TIPO_EMPRESA ADD (
  CONSTRAINT TIPO_EMPRESA_PK
 PRIMARY KEY
 (ID_TIPO));

ALTER TABLE REVISION ADD (
  PRIMARY KEY
 (ID_REVISION));

ALTER TABLE DOCUMENTO ADD (
  FOREIGN KEY (ID_TIPO) 
 REFERENCES TIPO_EMPRESA (ID_TIPO));

ALTER TABLE USUARIO ADD (
  FOREIGN KEY (ID_EMPRESA) 
 REFERENCES EMPRESA (ID_EMPRESA));

ALTER TABLE EMPRESA ADD (
  FOREIGN KEY (ID_TIPO) 
 REFERENCES TIPO_EMPRESA (ID_TIPO));

ALTER TABLE DOCS_CARGADO ADD (
  FOREIGN KEY (ID_DOCUMENTO) 
 REFERENCES DOCUMENTO (ID_DOCUMENTO),
  FOREIGN KEY (ID_EMPRESA) 
 REFERENCES EMPRESA (ID_EMPRESA),
  FOREIGN KEY (ID_ESTADO) 
 REFERENCES ESTADO (ID_ESTADO));

ALTER TABLE EMPRESA_NAT ADD (
  FOREIGN KEY (ID_PROFESION) 
 REFERENCES PROFESION (ID_PROFESION),
  FOREIGN KEY (ID_EMPRESA) 
 REFERENCES EMPRESA (ID_EMPRESA));

ALTER TABLE EMPRESA_JUR ADD (
  FOREIGN KEY (ID_EMPRESA) 
 REFERENCES EMPRESA (ID_EMPRESA),
  FOREIGN KEY (ID_ACTIVIDAD) 
 REFERENCES ACTVIDAD_ECO (ID_ACTIVIDAD));

ALTER TABLE REVISION ADD (
  FOREIGN KEY (ID_CARGA) 
 REFERENCES DOCS_CARGADO (ID_CARGA),
  FOREIGN KEY (ID_ESTADO) 
 REFERENCES ESTADO (ID_ESTADO));

